### ISSUE TITLE
cwd option not working

### ISSUE THREAD

**Issue by dbeckwith** [spalger/grunt-run#13]
I tried a simple test task:
```javascript
run: {
  cwd: 'some/sub/dir',
  cmd: 'pwd'
}
```
But it prints out the project's root directory, not the subdirectory.

**Comment by spalger** [comment]
`cwd` is actually [`options.cwd`](https://github.com/spalger/grunt-run#optionscwd). Can you try again like this:

```js
run: {
  options: {
     cwd: 'some/sub/dir'
  },
  cmd: 'pwd'
}
```

**Comment by dbeckwith** [comment]
Ah, yes, that fixes it. I was unclear where the `cwd` option should go.

**Comment by spalger** [comment]
Glad to hear that works :smile:
