### ISSUE TITLE
Update to grunt ~1.0.1

### ISSUE THREAD

**Issue by mischkl** [spalger/grunt-run#25]
At the moment npm throws an error about unmet peer dependencies when using Grunt 1.x. This also means our CI breaks. Please update the grunt peer dependency ASAP so we can use this plugin with Grunt 1.0! Thanks!

**Comment by spalger** [comment]
Thanks, released [0.5.3](https://github.com/spalger/grunt-run/releases/tag/v0.5.3) with a patch

**Comment by mischkl** [comment]
Great, thanks!
