### ISSUE TITLE
Broken ES5 compatibility

### ISSUE THREAD

**Issue by dhedey** [spalger/grunt-run#34]
As of https://github.com/spalger/grunt-run/commit/1fce0cae6b4caffe35682e88dbb20a8423d0e6b5 grunt-run has lost ES5 compatibility.

Ideally we'd add a babel compile (or remove the string templating) to still support people stuck on old versions of node.

**Comment by spalger** [comment]
What about that commit breaks compatibility with ES5? If it's the use of `child_process.execSync()` then the issue is the node version dependency. This method was added in node.js v0.11.12, which means that this library no longer works on node < 0.10 on windows. Is that the issue you're describing?

**Comment by spalger** [comment]
I just released version 0.8.0 which uses babel to transpile to support 0.12. If you still need grunt-run support would you mind giving it a shot?

**Comment by dhedey** [comment]
Yes, it appears to work well! Much appreciated @spalger
