### ISSUE TITLE
Unable to run .cmd file on MacOS spawn ENOENT Error

### ISSUE THREAD

**Issue by Bbemol** [spalger/grunt-run#35]
Hello,

I am not able to run a command file wich is in the same directory as my Gruntfile.
It shows the following error : 
`Running "run:dev" (run) task
>> Error: spawn upload-livy.cmd ENOENT
Warning: non-zero exit code -2 Use --force to continue.

Aborted due to warnings.`

However, I am able to run directly the command in my Terminal. Do you have any idea of how I can solve this issue ?

Thanks,
Benjamin

**Comment by Bbemol** [comment]
Found my error... I was accessing the file directly without "./" in front of the file name  : 
```
run: {
			dev: {
				cmd: "upload-livy.cmd"
			}
		}
```
And then, I had an EACSS error, but It was only CHMOD not well configured.
Hope it helps someone out there.
Thank you for the great plugin by the way!
Benjamin

**Comment by spalger** [comment]
Glad you got it working @bbemol!
